
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>


namespace SDNMediaModels.Feedback
{
    using SDNMediaModels.List;
    using SDNMediaModels.Logs;
    using System;
    using System.Collections.Generic;
    
    public partial class ProcessQueue : IProcessQueue
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProcessQueue()
        {
            this.FileMoveHistories = new HashSet<FileMoveHistory>();
        }
    
        public int pk_ProcessID { get; set; }
        public System.DateTime RequestTimestamp { get; set; }
        public int ProcessAction { get; set; }
        public int fk_AutomationPriority { get; set; }
        public int fk_AutomationStatus { get; set; }
        public string fk_UserID { get; set; }
        public Nullable<int> fk_MediaID { get; set; }
        public Nullable<int> NextAction { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FileMoveHistory> FileMoveHistories { get; set; }
        public virtual list_AutomationPriority list_AutomationPriority { get; set; }
        public virtual list_AutomationStatuses list_AutomationStatuses { get; set; }
    }
}
