
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>


namespace SDNMediaModels.Feedback
{
    using SDNMediaModels.Account;
    using SDNMediaModels.List;
    using System;
    using System.Collections.Generic;
    
    public partial class TaskQueue : ITaskQueue
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TaskQueue()
        {
            this.TaskQueue1 = new HashSet<TaskQueue>();
        }
    
        public int pk_TaskID { get; set; }
        public string TaskTitle { get; set; }
        public System.DateTime TaskStartTime { get; set; }
        public Nullable<System.DateTime> TaskEndTime { get; set; }
        public Nullable<int> fk_ParentTaskID { get; set; }
        public int fk_TaskStatus { get; set; }
        public string fk_TaskOwner { get; set; }
        public string TaskDetails { get; set; }
        public int fk_ActionType { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual list_AutomationActions list_AutomationActions { get; set; }
        public virtual list_AutomationStatuses list_AutomationStatuses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskQueue> TaskQueue1 { get; set; }
        public virtual TaskQueue TaskQueue2 { get; set; }
    }
}
