using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace MediaMaintenanceLibrary.Config
{
    /// <summary>
    /// SDNMediaManager configuration settings and constants
    /// </summary>
    public static class MediaManagerConfiguration
    {

        #region SQL Configuration....

        /// <summary>
        /// Username for accessing SQL Server
        /// </summary>
        public const string SqlUsername = "sa";

        /// <summary>
        /// Password for accessing SQL Server
        /// </summary>
        public const string SqlPassword = "A!12@lop^6";

        /// <summary>
        /// Hostname (Machine Name) of SQL Server machine
        /// </summary>
        public const string SqlHostname = "JimmyBeast-sdn";

        /// <summary>
        /// Database where SDN Media tables are stored
        /// </summary>
        public const string SqlDatabase = "SdnMedia";

        /// <summary>
        /// Name of SQL Server named instance, if applicable
        /// </summary>
        public const string SqlInstance = "/SQLEXPRESS";

        #endregion

        #region Event Log Configuration...

        //Event Log configuration details go here

        #endregion

        #region File Log Configuration...

        //Log file configuration details go here

        #endregion

        #region Regex Sanitization Configuration...

        /// <summary>
        /// Pattern used to sanitize episode filenames with period delimiters
        /// </summary>
        public const string TelevisionDottedRegexPattern = @"(.+).(S\d\d)(E\d\d).+(.mkv|.avi|.mp4)";

        /// <summary>
        /// Pattern used to sanitize episode filenames with space delimiters
        /// </summary>
        public const string TelevisionSpacedRegexPattern = @"(.+) (S\d\d)(E\d\d).+(.mkv|.avi|.mp4)";


        #endregion

        #region Program Configuration...

        /// <summary>
        /// Path to the log files generated by all components of the SDN Media Manager system
        /// </summary>
        public static string SDNLogPath { get; set; } = @"S:\~automation\logs\";

        #endregion

        #region WPF Configurations

        /// <summary>
        /// Url to make calls to the web api
        /// </summary>
        public static string WebAPIUrl { get; set; } = @"http://jimmysietsma.com:8077/api/";

        #endregion
    }
}
