
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>


namespace SDNMediaModels.List
{
    using System;
    using System.Collections.Generic;
    
    public partial class list_TaskTypes
    {
        public int pk_TaskTypeID { get; set; }
        public string TaskTypeName { get; set; }
        public int fk_TaskPriority { get; set; }
    
        public virtual list_AutomationPriority list_AutomationPriority { get; set; }
    }
}
