//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDNMediaModels.List
{
    using SDNMediaModels.Feedback;
    using System;
    using System.Collections.Generic;
    
    public partial class list_AutomationActions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public list_AutomationActions()
        {
            this.TaskQueues = new HashSet<TaskQueue>();
        }
    
        public int pk_ActionType { get; set; }
        public string ActionDescription { get; set; }
        public int fk_PriorityID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskQueue> TaskQueues { get; set; }
    }
}
