
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>


namespace SDNMediaModels.List
{
    using System;
    using System.Collections.Generic;

    public partial class list_MediaDrives
    {
        public int pk_MediaDriveID { get; set; }
        public string DriveLetter { get; set; }
        public int fk_MediaTypeID { get; set; }
        public string DriveSpace { get; set; }

        public virtual list_MediaTypes list_MediaTypes { get; set; }
    }
}
