//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDNMediaModels.List
{
    using SDNMediaModels.Account;
    using System;
    using System.Collections.Generic;
    
    public partial class list_permissionLevels
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public list_permissionLevels()
        {
            this.AspNetRoles = new HashSet<AspNetRole>();
        }
    
        public int pk_permissionLevelNum { get; set; }
        public string permissionLevelAuth { get; set; }
        public string permissionLevelDisplay { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetRole> AspNetRoles { get; set; }
    }
}
