//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDNMediaModels.List
{
    using SDNMediaModels.Feedback;
    using SDNMediaModels.Sort;
    using System;
    using System.Collections.Generic;
    
    public partial class list_AutomationStatuses
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public list_AutomationStatuses()
        {
            this.ProcessQueues = new HashSet<ProcessQueue>();
            this.UserRequests = new HashSet<UserRequest>();
            this.TaskQueues = new HashSet<TaskQueue>();
            this.sortItems = new HashSet<sortItem>();
        }
    
        public int pk_automationStatus { get; set; }
        public string automationStatusDisplay { get; set; }
        public int automationNextAction { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProcessQueue> ProcessQueues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserRequest> UserRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskQueue> TaskQueues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sortItem> sortItems { get; set; }
    }
}
