//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDNMediaModels.List
{
    using SDNMediaModels.Movie;
    using SDNMediaModels.Sort;
    using SDNMediaModels.Television;
    using System;
    using System.Collections.Generic;
    
    public partial class list_MediaTypes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public list_MediaTypes()
        {
            this.Movies = new HashSet<Movie>();
            this.TelevisionEpisodes = new HashSet<ITelevisionEpisode>();
            this.sortItems = new HashSet<sortItem>();
        }
    
        public int pk_MediaTypeID { get; set; }
        public string mediaTypeName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Movie> Movies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ITelevisionEpisode> TelevisionEpisodes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sortItem> sortItems { get; set; }
    }
}
