
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>


namespace SDNMediaModels.List
{
    using SDNMediaModels.Feedback;
    using System;
    using System.Collections.Generic;
    
    public partial class list_AutomationPriority
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public list_AutomationPriority()
        {
            this.list_TaskTypes = new HashSet<list_TaskTypes>();
            this.ProcessQueues = new HashSet<ProcessQueue>();
        }
    
        public int pk_PriorityID { get; set; }
        public string PriorityDescription { get; set; }
        public int PriorityLevel { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<list_TaskTypes> list_TaskTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProcessQueue> ProcessQueues { get; set; }
    }
}
