
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>


namespace SDNMediaModels.List
{
    using SDNMediaModels.Movie;
    using System;
    using System.Collections.Generic;
    
    public partial class list_MovieGenres
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public list_MovieGenres()
        {
            this.Movies = new HashSet<Movie>();
        }
    
        public int pk_GenreID { get; set; }
        public string GenreName { get; set; }
        public int GenreEnabled { get; set; }
        public string GenreHomePath { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Movie> Movies { get; set; }
    }
}
