
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>


namespace SDNMediaModels.Api
{
    using SDNMediaModels.Account;
    using System;
    using System.Collections.Generic;
    
    public partial class ApiToken
    {
        public int pk_tokenID { get; set; }
        public string Token { get; set; }
        public System.DateTime lastRefresh { get; set; }
        public string tokenSite { get; set; }
        public string fk_UserID { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
