//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDNetAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movie
    {
        public int pk_MovieID { get; set; }
        public string MovieTitle { get; set; }
        public Nullable<int> MovieYear { get; set; }
        public int fk_MovieGenre { get; set; }
        public string FilePath { get; set; }
        public string ImdbID { get; set; }
        public string TvdbID { get; set; }
        public int SubtitlesExist { get; set; }
        public Nullable<int> fk_MediaID { get; set; }
        public int fk_MediaType { get; set; }
    }
}
