//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDNMediaModels.Television
{
    using SDNMediaModels.Feedback;
    using SDNMediaModels.Logs;
    using System;
    using System.Collections.Generic;
    
    public partial class TelevisionShow : ITelevisionShow
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TelevisionShow()
        {
            this.PlaybackHistories = new HashSet<PlaybackHistory>();
            this.TelevisionEpisodes = new HashSet<ITelevisionEpisode>();
            this.TelevisionSeasons = new HashSet<ITelevisionSeason>();
            this.UserRequests = new HashSet<UserRequest>();
        }
    
        public int pk_ShowID { get; set; }
        public string ShowName { get; set; }
        public string ShowDriveLetter { get; set; }
        public string ShowHomePath { get; set; }
        public int ShowNumSeasons { get; set; }
        public int ShowNumEpisodes { get; set; }
        public string ShowAlbumArtPath { get; set; }
        public int IsEnabled { get; set; }
        public string TvdbID { get; set; }
        public string ImdbID { get; set; }
        public Nullable<int> fk_MediaType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlaybackHistory> PlaybackHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ITelevisionEpisode> TelevisionEpisodes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ITelevisionSeason> TelevisionSeasons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserRequest> UserRequests { get; set; }
    }
}
