
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>


namespace SDNMediaModels.Television
{
    using SDNMediaModels.Feedback;
    using SDNMediaModels.List;
    using SDNMediaModels.Logs;
    using SDNMediaModels.Sort;
    using System;
    using System.Collections.Generic;
    
    public partial class TelevisionEpisode : ITelevisionEpisode
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TelevisionEpisode()
        {
            this.PlaybackHistories = new HashSet<PlaybackHistory>();
            this.UserRequests = new HashSet<UserRequest>();
        }
    
        public int pk_EpisodeID { get; set; }
        public int fk_SeasonID { get; set; }
        public int fk_ShowID { get; set; }
        public int EpisodeNum { get; set; }
        public string EpisodePath { get; set; }
        public string EpisodePlayerPath { get; set; }
        public string EpisodeDisplayTitle { get; set; }
        public string EpisodeAlbumArtPath { get; set; }
        public int IsEnabled { get; set; }
        public Nullable<int> fk_MediaID { get; set; }
        public Nullable<int> fk_MediaType { get; set; }
    
        public virtual list_MediaTypes list_MediaTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlaybackHistory> PlaybackHistories { get; set; }
        public virtual sortItem sortItem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserRequest> UserRequests { get; set; }
        public virtual TelevisionSeason TelevisionSeason { get; set; }
        public virtual TelevisionShow TelevisionShow { get; set; }
    }
}
