
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>


namespace SDNMediaModels.Television
{
    using SDNMediaModels.Feedback;
    using SDNMediaModels.Logs;
    using System;
    using System.Collections.Generic;
    
    public partial class TelevisionSeason : ITelevisionSeason
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TelevisionSeason()
        {
            this.PlaybackHistories = new HashSet<PlaybackHistory>();
            this.TelevisionEpisodes = new HashSet<TelevisionEpisode>();
            this.UserRequests = new HashSet<UserRequest>();
        }
    
        public int pk_SeasonID { get; set; }
        public int fk_ShowID { get; set; }
        public string SeasonName { get; set; }
        public string SeasonHomePath { get; set; }
        public int SeasonNumEpisodes { get; set; }
        public string SeasonAlbumArtPath { get; set; }
        public int IsEnabled { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlaybackHistory> PlaybackHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TelevisionEpisode> TelevisionEpisodes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserRequest> UserRequests { get; set; }
        public virtual TelevisionShow TelevisionShow { get; set; }
    }
}
