
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>


namespace SDNMediaModels.Feedback
{
    using SDNMediaModels.Sort;
    using System;
    using System.Collections.Generic;
    
    public partial class DownloadQueue : IDownloadQueue
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DownloadQueue()
        {
            this.sortItems = new HashSet<sortItem>();
        }
    
        public string pk_torrentID { get; set; }
        public string TorrentName { get; set; }
        public Nullable<System.DateTime> DownloadFinished { get; set; }
        public Nullable<System.DateTime> DownloadStarted { get; set; }
        public string TorrentStatus { get; set; }
        public string TorrentPath { get; set; }
        public Nullable<int> DownloadDuration { get; set; }
        public int fileSize { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sortItem> sortItems { get; set; }
    }
}
